#if !canImport(ObjectiveC)
import XCTest

extension ColorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorTests = [
        ("testBlack", testBlack),
        ("testBlue", testBlue),
        ("testCyan", testCyan),
        ("testGreen", testGreen),
        ("testInitHexIntBlack", testInitHexIntBlack),
        ("testInitHexIntWhite", testInitHexIntWhite),
        ("testInitHexStringYellow", testInitHexStringYellow),
        ("testMagenta", testMagenta),
        ("testRed", testRed),
        ("testWhite", testWhite),
        ("testYellow", testYellow),
    ]
}

extension CompositeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompositeTests = [
        ("testBezierCurveBottomLeftTopRightEaseInEaseOut", testBezierCurveBottomLeftTopRightEaseInEaseOut),
        ("testBezierCurveRedDotsLinearT", testBezierCurveRedDotsLinearT),
        ("testBezierCurveRedDotsLinearX", testBezierCurveRedDotsLinearX),
        ("testBezierCurveRedDotsLinearY", testBezierCurveRedDotsLinearY),
        ("testBezierCurveTopLeftBottomRightEaseInEaseOut", testBezierCurveTopLeftBottomRightEaseInEaseOut),
        ("testBranchAllZeroFramedLeaves", testBranchAllZeroFramedLeaves),
        ("testBranchAllZeroFramedLeavesButNonZeroGroup", testBranchAllZeroFramedLeavesButNonZeroGroup),
        ("testLeafAxisAlignedBoundingBox", testLeafAxisAlignedBoundingBox),
        ("testLeafAxisAlignedBoundingBoxNonZeroFrame", testLeafAxisAlignedBoundingBoxNonZeroFrame),
        ("testResizedToFitContentsBranchScaleAndTranslation", testResizedToFitContentsBranchScaleAndTranslation),
        ("testResizedToFitContentsBranchScaleAndTranslation2", testResizedToFitContentsBranchScaleAndTranslation2),
        ("testResizedToFitContentsLeafNoChange", testResizedToFitContentsLeafNoChange),
        ("testResizedToFitContentsLeafNoTranslation", testResizedToFitContentsLeafNoTranslation),
        ("testResizedToFitContentsLeafScaleAndTranslation", testResizedToFitContentsLeafScaleAndTranslation),
        ("testTranslateGroup", testTranslateGroup),
        ("testTranslateLeaf", testTranslateLeaf),
    ]
}

extension StyledPathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StyledPathTests = [
        ("testResizedToFitContents", testResizedToFitContents),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ColorTests.__allTests__ColorTests),
        testCase(CompositeTests.__allTests__CompositeTests),
        testCase(StyledPathTests.__allTests__StyledPathTests),
    ]
}
#endif
