#if !canImport(ObjectiveC)
import XCTest

extension CubicBezierCurveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CubicBezierCurveTests = [
        ("testBoundingBoxRender", testBoundingBoxRender),
        ("testLength", testLength),
        ("testRotatedRender", testRotatedRender),
        ("testScaledRender", testScaledRender),
        ("testSimplifiedRender", testSimplifiedRender),
        ("testSimplify", testSimplify),
        ("testSlopeDown", testSlopeDown),
        ("testSlopeUp", testSlopeUp),
        ("testSplit", testSplit),
        ("testSplitRender", testSplitRender),
        ("testTranslatedByRender", testTranslatedByRender),
        ("testUpAndDown", testUpAndDown),
        ("testXsAtY", testXsAtY),
        ("testYsAtX", testYsAtX),
    ]
}

extension EllipseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EllipseTests = [
        ("testEllipse", testEllipse),
    ]
}

extension LinearBezierCurveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LinearBezierCurveTests = [
        ("testInit", testInit),
        ("testPointAtT", testPointAtT),
        ("testXsAtY", testXsAtY),
        ("testYsAtX", testYsAtX),
    ]
}

extension PathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathTests = [
        ("testAddCurve", testAddCurve),
        ("testCustomStringConvertible", testCustomStringConvertible),
        ("testInitWithCGRect", testInitWithCGRect),
        ("testMoveTo", testMoveTo),
        ("testMoveToLineTo", testMoveToLineTo),
        ("testSimplified", testSimplified),
    ]
}

extension QuadraticBezierCurveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuadraticBezierCurveTests = [
        ("testBezierCurveTsAtX", testBezierCurveTsAtX),
        ("testBezierCurveTsAtY", testBezierCurveTsAtY),
        ("testBezierCurveXsAtY", testBezierCurveXsAtY),
    ]
}

extension TransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransformTests = [
        ("testRectangleTranslatedByALittleInBothDirectionsNotEqual", testRectangleTranslatedByALittleInBothDirectionsNotEqual),
        ("testRectangleTranslatedByZeroZeroEqual", testRectangleTranslatedByZeroZeroEqual),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CubicBezierCurveTests.__allTests__CubicBezierCurveTests),
        testCase(EllipseTests.__allTests__EllipseTests),
        testCase(LinearBezierCurveTests.__allTests__LinearBezierCurveTests),
        testCase(PathTests.__allTests__PathTests),
        testCase(QuadraticBezierCurveTests.__allTests__QuadraticBezierCurveTests),
        testCase(TransformTests.__allTests__TransformTests),
    ]
}
#endif
