#if !canImport(ObjectiveC)
import XCTest

extension AngleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AngleTests = [
        ("testAngleDegrees", testAngleDegrees),
        ("testAngleRadiansToDegrees", testAngleRadiansToDegrees),
    ]
}

extension CollisionDetectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollisionDetectionTests = [
        ("testContainsPointInRectFalse", testContainsPointInRectFalse),
        ("testContainsPointInRectTrue", testContainsPointInRectTrue),
        ("testConvexHull", testConvexHull),
        ("testEqualRectsIntersectingTrue", testEqualRectsIntersectingTrue),
        ("testPolygonContainsPointFalse", testPolygonContainsPointFalse),
        ("testPolygonContainsPointTrue", testPolygonContainsPointTrue),
        ("testRectangleDiamondSeparatedIntersectingFalse", testRectangleDiamondSeparatedIntersectingFalse),
        ("testRectsSeparatedAboveIntersectingFalse", testRectsSeparatedAboveIntersectingFalse),
        ("testXsAtYRect", testXsAtYRect),
        ("testYsAtXRect", testYsAtXRect),
    ]
}

extension LineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LineTests = [
        ("testHorizontalLinePerpendicular", testHorizontalLinePerpendicular),
        ("testInitWithSegment", testInitWithSegment),
        ("testLineLengthHorizontal", testLineLengthHorizontal),
        ("testLineLengthPositiveDiagonal", testLineLengthPositiveDiagonal),
        ("testLineLengthVertical", testLineLengthVertical),
        ("testRayInitWithSegmentHorizontalLeft", testRayInitWithSegmentHorizontalLeft),
        ("testRayInitWithSegmentHorizontalRight", testRayInitWithSegmentHorizontalRight),
        ("testRayInitWithSegmentVerticalDown", testRayInitWithSegmentVerticalDown),
        ("testRayInitWithSegmentVerticalUp", testRayInitWithSegmentVerticalUp),
        ("testRayPointAtDistance", testRayPointAtDistance),
        ("testRayPointAtDistanceHorizontal", testRayPointAtDistanceHorizontal),
        ("testRayPointAtDistanceVertical", testRayPointAtDistanceVertical),
        ("testSlantedLinePerpendicular", testSlantedLinePerpendicular),
        ("testVerticalLinePerpendicular", testVerticalLinePerpendicular),
    ]
}

extension PointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PointTests = [
        ("testDistanceTo", testDistanceTo),
        ("testPointAddition", testPointAddition),
        ("testPointDivision", testPointDivision),
        ("testPointMultiply", testPointMultiply),
        ("testPointSubtraction", testPointSubtraction),
        ("testReflectedOverLine", testReflectedOverLine),
        ("testReflectedOverXAxis", testReflectedOverXAxis),
        ("testReflectedOverYAxis", testReflectedOverYAxis),
        ("testRotated90DegreesAroundOrigin", testRotated90DegreesAroundOrigin),
        ("testRotated90DegressAroundPoint", testRotated90DegressAroundPoint),
        ("testRotateNoChange", testRotateNoChange),
        ("testScaledDoubleFromOrigin", testScaledDoubleFromOrigin),
        ("testScaledNoChange", testScaledNoChange),
        ("testScaledTripleFromReferencePoint", testScaledTripleFromReferencePoint),
        ("testValueForAxis", testValueForAxis),
    ]
}

extension PolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PolygonTests = [
        ("testBlockCTriangulated", testBlockCTriangulated),
        ("testBlockCTriangulatedClockwise", testBlockCTriangulatedClockwise),
        ("testConvexityFalse", testConvexityFalse),
        ("testHouseTriangulated", testHouseTriangulated),
        ("testPentagonConvexityTrue", testPentagonConvexityTrue),
        ("testPolygonOrderClockwise", testPolygonOrderClockwise),
        ("testPolygonOrderCounterClockwise", testPolygonOrderCounterClockwise),
        ("testReduce", testReduce),
        ("testSquareConvexityTrue", testSquareConvexityTrue),
        ("testSquareTriangulated", testSquareTriangulated),
        ("testSum", testSum),
        ("testTriangleContainsPointFalse", testTriangleContainsPointFalse),
        ("testTriangleContainsPointTrue", testTriangleContainsPointTrue),
        ("testTriangleEqualToTriangulatedSelf", testTriangleEqualToTriangulatedSelf),
        ("testVertexConvexFalse", testVertexConvexFalse),
        ("testVertexConvexTrue", testVertexConvexTrue),
    ]
}

extension RectangleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RectangleTests = [
        ("testNormalizedFlipX", testNormalizedFlipX),
        ("testNormalizedFlipXAndY", testNormalizedFlipXAndY),
        ("testNormalizedFlipY", testNormalizedFlipY),
        ("testNormalizedIdentity", testNormalizedIdentity),
        ("testRectangleNonEmptySum", testRectangleNonEmptySum),
        ("testRectangleSum", testRectangleSum),
        ("testScaled", testScaled),
        ("testScaledAroundCenter", testScaledAroundCenter),
        ("testScaledBy", testScaledBy),
        ("testScaledByAroundCenter", testScaledByAroundCenter),
        ("testScaledByHeightOnly", testScaledByHeightOnly),
        ("testScaledByHeightOnlyAroundCenter", testScaledByHeightOnlyAroundCenter),
        ("testScaledByWidthOnly", testScaledByWidthOnly),
        ("testScaledByWidthOnlyAroundCenter", testScaledByWidthOnlyAroundCenter),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AngleTests.__allTests__AngleTests),
        testCase(CollisionDetectionTests.__allTests__CollisionDetectionTests),
        testCase(LineTests.__allTests__LineTests),
        testCase(PointTests.__allTests__PointTests),
        testCase(PolygonTests.__allTests__PolygonTests),
        testCase(RectangleTests.__allTests__RectangleTests),
    ]
}
#endif
